name: Matrix demo
on: push
jobs:
  build:
    continue-on-error: true 
    strategy:
      matrix:  # idea is run the same job with different configurations. like different node versions
        node-version: [12, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include: # allow u to add a list with dashes of key values that should be included with bunch of combinations
          - node-version: 18
            operating-system: ubuntu-latest # this version 18 only work on ubuntu
        exclude:
          - node-version: 12
            operating-system: windows-latest # version 12 not work on windows
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Intall Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 14 # ${{matrix.node-version}}
      - name: Intall Dependencies
        run: npm ci
      - name: Build project
        run: npm run build 