name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact-name: 
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: The name of the deployable artifact files
        value: ${{jobs.deploy.outcome}}
    secrets:
      some-secret:
        required: false # we can use this secret when we use this file
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }} # take dynamic inputs
      - name: Output information
        run: echo "Deploying & uploading..."

        # in the file we use this .yml file we give an input like
        # with:
        #   artifact-name: dist-files #this is the input   